return {
  ["armmex"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corlab"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armcom"] = {
    HEIGHT = 85,
    FORWARD = -125,
    ROTATION = 0,
    SIDE = 15,
  },
  ["corbw"] = {
    HEIGHT = 35,
    FORWARD = -165,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armca"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corck"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armlab"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armrock"] = {
    HEIGHT = 85,
    FORWARD = -140,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armck"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corak"] = {
    HEIGHT = 90,
    FORWARD = -150,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcrwh"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armfig"] = {
    HEIGHT = 55,
    FORWARD = -240,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corgeo"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcan"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corsumo"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armfboy"] = {
    HEIGHT = 85,
    FORWARD = -160,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armpw"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corfav"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corwolv"] = {
    HEIGHT = 75,
    FORWARD = -125,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armmav"] = {
    HEIGHT = 140,
    FORWARD = -200,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcom"] = {
    HEIGHT = 155,
    FORWARD = -370,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corllt"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armflea"] = {
    HEIGHT = 50,
    FORWARD = -70,
    SIDE = 10,
    ROTATION = 0,
  },
}