return {
  ["armmav"] = {
    HEIGHT = 200,
    FORWARD = -340,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armcom"] = {
    HEIGHT = 85,
    FORWARD = -125,
    ROTATION = 0,
    SIDE = 15,
  },
  ["armflea"] = {
    HEIGHT = 50,
    FORWARD = -70,
    SIDE = 10,
    ROTATION = 0,
  },
  ["corbw"] = {
    HEIGHT = 35,
    FORWARD = -165,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armck"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corgeo"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corfav"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armpw"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armlab"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corwolv"] = {
    HEIGHT = 75,
    FORWARD = -125,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corak"] = {
    HEIGHT = 90,
    FORWARD = -150,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcom"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armmex"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armrock"] = {
    HEIGHT = 85,
    FORWARD = -140,
    ROTATION = 0,
    SIDE = 0,
  },
}