return {
  ["armmav"] = {
    HEIGHT = 195,
    FORWARD = -450,
    SIDE = -40,
    ROTATION = 0,
  },
  ["armcom"] = {
    HEIGHT = 130,
    FORWARD = -320,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armflea"] = {
    HEIGHT = 130,
    FORWARD = -300,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corbw"] = {
    HEIGHT = 130,
    FORWARD = -300,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armck"] = {
    HEIGHT = 130,
    FORWARD = -300,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corgeo"] = {
    HEIGHT = 130,
    FORWARD = -300,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corfav"] = {
    HEIGHT = 130,
    FORWARD = -300,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armpw"] = {
    HEIGHT = 130,
    FORWARD = -300,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armlab"] = {
    HEIGHT = 130,
    FORWARD = -300,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corwolv"] = {
    HEIGHT = 130,
    FORWARD = -310,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corak"] = {
    HEIGHT = 130,
    FORWARD = -300,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcom"] = {
    HEIGHT = 130,
    FORWARD = -300,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armmex"] = {
    HEIGHT = 130,
    FORWARD = -300,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armrock"] = {
    HEIGHT = 130,
    FORWARD = -300,
    ROTATION = 0,
    SIDE = 0,
  },
}