return {
  ["armcom"] = {
    HEIGHT = 35,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["cordemon"] = {
    HEIGHT = 110,
    FORWARD = -120,
    ROTATION = 0,
    SIDE = -25,
  },
  ["armsam"] = {
    HEIGHT = 55,
    FORWARD = 185,
    ROTATION = 0,
    SIDE = -40,
  },
  ["corshiva"] = {
    HEIGHT = 65,
    FORWARD = -90,
    ROTATION = 0,
    SIDE = 45,
  },
  ["corsok"] = {
    HEIGHT = 175,
    FORWARD = -150,
    ROTATION = 0,
    SIDE = -25,
  },
  ["corack"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armfast"] = {
    HEIGHT = 55,
    FORWARD = 185,
    ROTATION = 0,
    SIDE = -40,
  },
  ["armlab"] = {
    HEIGHT = 0,
    FORWARD = -5,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armmav"] = {
    HEIGHT = 55,
    FORWARD = -280,
    ROTATION = 0,
    SIDE = 205,
  },
  ["armthund"] = {
    HEIGHT = 0,
    FORWARD = -5,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcom"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 80,
  },
  ["armck"] = {
    HEIGHT = 55,
    FORWARD = 185,
    ROTATION = 0,
    SIDE = -40,
  },
  ["corllt"] = {
    HEIGHT = 0,
    FORWARD = 95,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corkorg"] = {
    HEIGHT = 175,
    FORWARD = -150,
    ROTATION = 0,
    SIDE = -25,
  },
  ["armvang"] = {
    HEIGHT = 25,
    FORWARD = -55,
    ROTATION = 0,
    SIDE = 20,
  },
  ["armstump"] = {
    HEIGHT = 125,
    FORWARD = -125,
    ROTATION = 0,
    SIDE = -20,
  },
  ["corfav"] = {
    HEIGHT = 0,
    FORWARD = -75,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armshltx"] = {
    HEIGHT = 25,
    FORWARD = -55,
    ROTATION = 0,
    SIDE = 20,
  },
  ["armsilo"] = {
    HEIGHT = 90,
    FORWARD = -85,
    ROTATION = 0,
    SIDE = 20,
  },
  ["armfboy"] = {
    HEIGHT = 100,
    FORWARD = -140,
    ROTATION = 0,
    SIDE = 45,
  },
  ["armpw"] = {
    HEIGHT = 55,
    FORWARD = -280,
    ROTATION = 0,
    SIDE = -140,
  },
  ["armflea"] = {
    HEIGHT = 10,
    FORWARD = 40,
    ROTATION = 0,
    SIDE = 60,
  },
  ["corwolv"] = {
    HEIGHT = 10,
    FORWARD = 40,
    ROTATION = 0,
    SIDE = 60,
  },
  ["armmanni"] = {
    HEIGHT = 55,
    FORWARD = -130,
    ROTATION = 0,
    SIDE = 20,
  },
  ["corsilo"] = {
    HEIGHT = 190,
    FORWARD = -275,
    ROTATION = 0,
    SIDE = -205,
  },
  ["corcat"] = {
    HEIGHT = 190,
    FORWARD = -245,
    ROTATION = 0,
    SIDE = 130,
  },
  ["corfmd"] = {
    HEIGHT = 25,
    FORWARD = -55,
    ROTATION = 0,
    SIDE = 20,
  },
}