return {
  ["armmex"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armlab"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armcom"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corbw"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armfast"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["cordemon"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armsam"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcom"] = {
    HEIGHT = 0,
    FORWARD = 0,
    SIDE = 80,
    ROTATION = 0,
  },
  ["corshiva"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corsok"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corack"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corllt"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corak"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armmav"] = {
    HEIGHT = 0,
    FORWARD = 0,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armthund"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armrock"] = {
    HEIGHT = 0455,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armck"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corfav"] = {
    HEIGHT = 0,
    FORWARD = 0,
    SIDE = -55,
    ROTATION = 0,
  },
  ["armvang"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armflea"] = {
    HEIGHT = 0,
    FORWARD = 0,
    SIDE = 60,
    ROTATION = 0,
  },
  ["armstump"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corgeo"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armshltx"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armsilo"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armfboy"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armpw"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corkorg"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corwolv"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armmanni"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corsilo"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcat"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corfmd"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
}