return {
  ["armcom"] = {
    HEIGHT = 20,
    FORWARD = -75,
    SIDE = 10,
    ROTATION = 0,
  },
  ["corshiva"] = {
    HEIGHT = 65,
    FORWARD = -90,
    SIDE = 45,
    ROTATION = 0,
  },
  ["corsok"] = {
    HEIGHT = 175,
    FORWARD = -150,
    SIDE = -25,
    ROTATION = 0,
  },
  ["armthund"] = {
    HEIGHT = 0,
    FORWARD = -5,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armck"] = {
    HEIGHT = 55,
    FORWARD = 185,
    ROTATION = 0,
    SIDE = -40,
  },
  ["armflea"] = {
    HEIGHT = 10,
    FORWARD = 40,
    ROTATION = 0,
    SIDE = 60,
  },
  ["armfig"] = {
    HEIGHT = 70,
    FORWARD = -25,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corcan"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corfav"] = {
    HEIGHT = 55,
    FORWARD = -140,
    ROTATION = 0,
    SIDE = -55,
  },
  ["corsilo"] = {
    HEIGHT = 190,
    FORWARD = -275,
    SIDE = -205,
    ROTATION = 0,
  },
  ["corcat"] = {
    HEIGHT = 190,
    FORWARD = -245,
    SIDE = 130,
    ROTATION = 0,
  },
  ["armmex"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corlab"] = {
    HEIGHT = 0,
    FORWARD = 0,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corkorg"] = {
    HEIGHT = 175,
    FORWARD = -150,
    SIDE = -25,
    ROTATION = 0,
  },
  ["corbw"] = {
    HEIGHT = 35,
    FORWARD = -235,
    SIDE = 0,
    ROTATION = 0,
  },
  ["cordemon"] = {
    HEIGHT = 110,
    FORWARD = -120,
    SIDE = -25,
    ROTATION = 0,
  },
  ["armsam"] = {
    HEIGHT = 55,
    FORWARD = 185,
    SIDE = -40,
    ROTATION = 0,
  },
  ["corfmd"] = {
    HEIGHT = 25,
    FORWARD = -55,
    SIDE = 20,
    ROTATION = 0,
  },
  ["corack"] = {
    HEIGHT = 0,
    FORWARD = 0,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corck"] = {
    HEIGHT = 0,
    FORWARD = 0,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corak"] = {
    HEIGHT = 105,
    FORWARD = -130,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corcrwh"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armrock"] = {
    HEIGHT = -455,
    FORWARD = -470,
    SIDE = -120,
    ROTATION = 0,
  },
  ["armmav"] = {
    HEIGHT = 50,
    FORWARD = -175,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corsumo"] = {
    HEIGHT = 0,
    FORWARD = 0,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armca"] = {
    HEIGHT = 0,
    FORWARD = 0,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armvang"] = {
    HEIGHT = 25,
    FORWARD = -55,
    SIDE = 20,
    ROTATION = 0,
  },
  ["armstump"] = {
    HEIGHT = 125,
    FORWARD = -125,
    SIDE = -20,
    ROTATION = 0,
  },
  ["corllt"] = {
    HEIGHT = 0,
    FORWARD = 95,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corgeo"] = {
    HEIGHT = 35,
    FORWARD = -75,
    SIDE = 0,
    ROTATION = 0,
  },
  ["armsilo"] = {
    HEIGHT = 90,
    FORWARD = -85,
    SIDE = 20,
    ROTATION = 0,
  },
  ["armshltx"] = {
    HEIGHT = 25,
    FORWARD = -55,
    SIDE = 20,
    ROTATION = 0,
  },
  ["armpw"] = {
    HEIGHT = 55,
    FORWARD = -280,
    SIDE = -140,
    ROTATION = 0,
  },
  ["armfboy"] = {
    HEIGHT = 50,
    FORWARD = -80,
    SIDE = 0,
    ROTATION = 0,
  },
  ["corwolv"] = {
    HEIGHT = 535,
    FORWARD = -540,
    SIDE = 60,
    ROTATION = 0,
  },
  ["armmanni"] = {
    HEIGHT = 55,
    FORWARD = -130,
    SIDE = 20,
    ROTATION = 0,
  },
  ["corcom"] = {
    HEIGHT = 155,
    FORWARD = -285,
    SIDE = 80,
    ROTATION = 0,
  },
  ["armfast"] = {
    HEIGHT = 55,
    FORWARD = 185,
    SIDE = -40,
    ROTATION = 0,
  },
  ["armlab"] = {
    HEIGHT = 0,
    FORWARD = -5,
    SIDE = 0,
    ROTATION = 0,
  },
}