return {
  ["armbanth"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armca"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armck"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armcom"] = {
    FORWARD = -320,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armfast"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armfboy"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armfig"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armflea"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armlab"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armmav"] = {
    FORWARD = -450,
    HEIGHT = 195,
    ROTATION = 0,
    SIDE = -40,
  },
  ["armmex"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armpw"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armrock"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armthor"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["armvang"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corak"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corbw"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcan"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corck"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcom"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corcrwh"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["cordemon"] = {
    FORWARD = -300,
    HEIGHT = 151,
    ROTATION = 0,
    SIDE = 0,
  },
  ["cordrag"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corfav"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corgeo"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corlab"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corllt"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["cormort"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corpyro"] = {
    FORWARD = -265,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corrad"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corrl"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corstorm"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corsumo"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corthud"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corveng"] = {
    FORWARD = -300,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
  ["corwolv"] = {
    FORWARD = -310,
    HEIGHT = 130,
    ROTATION = 0,
    SIDE = 0,
  },
}